#ifndef _BOARD_CONFIG_H_
#define _BOARD_CONFIG_H_

// Pin mapping derived from debug/sch/Netlist_Schematic1_2025-09-30.enet

#include <driver/gpio.h>

#define AUDIO_INPUT_SAMPLE_RATE  24000
#define AUDIO_OUTPUT_SAMPLE_RATE 24000

#define AUDIO_I2S_GPIO_MCLK GPIO_NUM_6
#define AUDIO_I2S_GPIO_WS   GPIO_NUM_12
#define AUDIO_I2S_GPIO_BCLK GPIO_NUM_14
#define AUDIO_I2S_GPIO_DIN  GPIO_NUM_11
#define AUDIO_I2S_GPIO_DOUT GPIO_NUM_13

#define AUDIO_CODEC_PA_PIN       GPIO_NUM_3
#define AUDIO_CODEC_I2C_SDA_PIN  GPIO_NUM_5
#define AUDIO_CODEC_I2C_SCL_PIN  GPIO_NUM_4
#define AUDIO_CODEC_ES8311_ADDR  ES8311_CODEC_DEFAULT_ADDR

#define BUILTIN_LED_GPIO        GPIO_NUM_36
#define BOOT_BUTTON_GPIO        GPIO_NUM_0

#define DISPLAY_WIDTH   480
#define DISPLAY_HEIGHT  320
#define DISPLAY_MIRROR_X true
#define DISPLAY_MIRROR_Y false
#define DISPLAY_SWAP_XY false
#define DISPLAY_INVERT_COLOR true

#define DISPLAY_OFFSET_X  0
#define DISPLAY_OFFSET_Y  0

#define DISPLAY_BACKLIGHT_PIN GPIO_NUM_3
#define DISPLAY_BACKLIGHT_OUTPUT_INVERT false

#define DISPLAY_SPI_SCLK_PIN    GPIO_NUM_16
#define DISPLAY_SPI_MOSI_PIN    GPIO_NUM_17
#define DISPLAY_SPI_CS_PIN      GPIO_NUM_15
#define DISPLAY_SPI_DC_PIN      GPIO_NUM_7
#define DISPLAY_SPI_RESET_PIN   GPIO_NUM_18
#define DISPLAY_SPI_SCLK_HZ     (40 * 1000 * 1000)

#define CAMERA_PIN_D0 GPIO_NUM_45
#define CAMERA_PIN_D1 GPIO_NUM_35
#define CAMERA_PIN_D2 GPIO_NUM_37
#define CAMERA_PIN_D3 GPIO_NUM_38
#define CAMERA_PIN_D4 GPIO_NUM_39
#define CAMERA_PIN_D5 GPIO_NUM_40
#define CAMERA_PIN_D6 GPIO_NUM_41
#define CAMERA_PIN_D7 GPIO_NUM_42
#define CAMERA_PIN_XCLK GPIO_NUM_10
#define CAMERA_PIN_PCLK GPIO_NUM_46
#define CAMERA_PIN_VSYNC GPIO_NUM_47
#define CAMERA_PIN_HREF GPIO_NUM_48
#define CAMERA_PIN_SIOC GPIO_NUM_21
#define CAMERA_PIN_SIOD GPIO_NUM_1
#define CAMERA_PIN_PWDN GPIO_NUM_NC
#define CAMERA_PIN_RESET GPIO_NUM_NC
#define XCLK_FREQ_HZ 20000000

#endif // _BOARD_CONFIG_H_
